language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 7.0
  - hhvm

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  
notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
